### ISSUE TITLE
could not determine kind of name for C.ftdi_tciflush

### ISSUE THREAD

**Issue by YJ-L-2017** [ziutek/ftdi#14]
# github.com/ziutek/ftdi
/home/yj/go/pkg/mod/github.com/ziutek/ftdi@v0.0.1/device.go:386:21: could not determine kind of name for C.ftdi_tciflush
/home/yj/go/pkg/mod/github.com/ziutek/ftdi@v0.0.1/device.go:396:21: could not determine kind of name for C.ftdi_tcioflush
/home/yj/go/pkg/mod/github.com/ziutek/ftdi@v0.0.1/device.go:391:21: could not determine kind of name for C.ftdi_tcoflush

**Comment by matiah** [comment]
I also get the same error.

**Comment by ziutek** [comment]
Fixed. Thanks!
